### ISSUE TITLE
Add support for large raster on Worker instances

### ISSUE THREAD

**Issue by hectcastro** [project-icp/bee-pollinator-app#127]
The `Worker` instances require a ~2GB raster file to function properly when deployed to AWS. Determine the best method of getting this file into the AMIs.

**Comment by mmcfarland** [comment]
Raster is available at ` s3://icp-cdl-data/cdl_reclass_lzw_5070.tif`, in the stg account.

**Comment by mmcfarland** [comment]
Additionally, the yield model has a default expectation on the path

 https://github.com/project-icp/bee-pollinator-app/blob/develop/src/icp/pollinator/src/pollinator/crop_yield.py#L16

which can be overridden by the calling client code

https://github.com/project-icp/bee-pollinator-app/blob/develop/src/icp/pollinator/src/pollinator/crop_yield.py#L194

We can extract that out to an ENV variable to accommodate this task.

**Comment by mmcfarland** [comment]
Closed via #136
