### ISSUE TITLE
Check for lint Ansible task failing

### ISSUE THREAD

**Issue by hectcastro** [project-icp/bee-pollinator-app#135]
The Ansible task named `Check for lint` is failing. Under the covers, it runs `npm run lint`.

See: http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-app-and-worker/1/console

**Comment by mmcfarland** [comment]
Closed via #148

http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/25/console
