### ISSUE TITLE
Impose maximum field size

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#138]
The model was designed for use on field sizes up to 400 acres, we should enforce a limit near that value for drawn areas.

**Comment by arottersman** [comment]
Updating the max to 410 acres is just a one-line change -- should its work include porting over the MMW fancy modals?
![screen shot 2017-02-02 at 3 08 16 pm](https://cloud.githubusercontent.com/assets/7633670/22566356/903af654-e959-11e6-9bbd-1e778eed5ec1.png)

**Comment by mmcfarland** [comment]
Bummer that we didn't capture that before we cut over.  I think it should be relatively simple to copy over the nicer modal, let's do it unless it begins to appear challenging.

**Comment by arottersman** [comment]
For max field size should it be exactly `400`? And should it be inclusive or exclusive?

**Comment by mmcfarland** [comment]
Might as well keep it at 400 inclusive, if we need to tweak it we can, we can also check the impact on execution time if they find they need it bigger.
