### ISSUE TITLE
Compare View Issues

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#141]
When opening the Compare view immediately after the Modeling view, without giving the Current Conditions scenario run to complete, initially we see the spinners. Subsequently, after the spinning stops, we see this:

![image](https://cloud.githubusercontent.com/assets/1430060/22531632/2fa241ca-e8b0-11e6-9bdf-b2a59dd9e540.png)

This is likely because we [only update the charts once the spinning stops](https://github.com/project-icp/bee-pollinator-app/blob/c4a5cad8f0ab80a4d5fa8e156ca8ba3a26be042e/src/icp/js/src/compare/views.js#L217-L220), but if they are not initialized with the right variables for charting it doesn't render correctly.

When the view is reinitialized, for example by going back to Modeling and coming back to Compare, the chart renders correctly.

This can be seen in action here:

![2017-02-01 18 46 36](https://cloud.githubusercontent.com/assets/1430060/22531688/879d064e-e8b0-11e6-9cfc-c52575c86dca.gif)

Another issue is that we seem to not update scenarios until they have been made active. Thus, after having made changes to Current Conditions, if the user goes directly to Compare view, other scenarios will be stale. But if they go to each scenario first and then go to the Compare view, the results are accurate.

![2017-02-01 19 03 58](https://cloud.githubusercontent.com/assets/1430060/22531799/5658db5c-e8b1-11e6-8a88-60dec225276d.gif)

A third issue is that if any changes in the Modeling view lead to additional chartable crops being added, or some removed, and the user goes to the Compare view before results come back, then Compare view isn't updated correctly. It keeps the list of chartable crops [during initialization](https://github.com/project-icp/bee-pollinator-app/blob/c4a5cad8f0ab80a4d5fa8e156ca8ba3a26be042e/src/icp/js/src/compare/views.js#L181-L189), and doesn't update them.

**Comment by rajadain** [comment]
One of the main causes for these failures is the behavior introduced in https://github.com/project-icp/bee-pollinator-app/pull/103, namely that of stale scenarios not updating themselves until their tab is made active. This leads to the Compare View having stale results, as described here, until that scenario's tab is viewed first in Model view.

I can envision two approaches to fix this:

 1. Going to Compare view forces recalculation of every scenario that is out of date.
    + ➕  Requires no additional user input
    + ➕  With individual spinners for each scenario it is plainly communicated that they are updating.
    - ➖  May cause clogging if there are many affected scenarios, such as after an update to Current Conditions
 2. Going to Compare view does nothing, but each stale scenario is marked as such and requires the user to click to update it
    + ➕  It is plainly communicated that the results are stale, and there is an obvious way to update them
    + ➕  Will cause no automatic clogging
    - ➖  Requires additional user input
    - ➖  User can still trigger many updates, if many scenarios are stale, manually causing the clogging.
    - ➖  May require involving Design Team to figure out button placement

Any preference, @mmcfarland ?

**Comment by mmcfarland** [comment]
Yeah, I was picturing along the lines of option 1.  Basically, if the hash doesn't match and it's getting activated, either by tab or compare, then the scenario needs to request calc.  This is basically the behavior of MMW except that the results are out of date not because they were specifically not recalculated, but because the "precipitation input" is normalized across all scenarios, effectively making their results stale.

There will be a pile up if there are a lot of scenarios and the edit is to current conditions, as you say - but I don't think that can be avoided and we can hope that all the correcting is done up front.

**Comment by rajadain** [comment]
Got it, thanks!
