### ISSUE TITLE
Fix scenario renaming

### ISSUE THREAD

**Issue by arottersman** [project-icp/bee-pollinator-app#150]
When renaming a scenario:
- the cursor begins on the lefthand side
- when you try to select text by clicking it, rename mode exits and you end up just clicking the tab
- when you press enter but don't change anything you get warned that there's already a scenario with that name
- you can rename to a blank string

Could bring over from MMW the work done for https://github.com/WikiWatershed/model-my-watershed/pull/1683 .

**Comment by arottersman** [comment]
@ajrobbins @jfrankl Should the update mimic MMW prime where the tab text becomes editable, or should it mimic the change made most recently (https://github.com/WikiWatershed/model-my-watershed/pull/1984) and create a rename modal?

**Comment by ajrobbins** [comment]
The former - tab text becomes editable
