### ISSUE TITLE
Add single SVG pattern to "cover crop" types

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#154]
In order to distinguish between cover crop and base crop types, we need to add a single SVG pattern to be used on top of all cover crop types, similarly to MMW.

Additionally, regroup the land cover types to have cover crop types follow the entire list of base crop types, to separate visually and reduce the chance that they'd be confused with their base.

**Comment by rajadain** [comment]
From what I can tell, I don't think we can use a single SVG pattern "overlaid" on a color. The base color is very much a part of the pattern itself, and must be specified in the pattern. Thus, we'll probably have a pattern for each crop type, including those that aren't cover types, just some with shapes and others with solid colors. I'll confirm this with Design.

**Comment by rajadain** [comment]
How does this look?

![image](https://cloud.githubusercontent.com/assets/1430060/22941466/7fab9b5a-f2b3-11e6-8853-13d2ff41b26e.png)

I've chosen white lines for darker colors, and black lines for lighter colors. The lines have 0.5 thickness, and the pattern is 5×5. The screenshot is in a scenario, showing shapes drawn in Current Conditions, thus have some transparency. The bottom two shapes are Cherries and Cherries with Cover Crop, to show contrast.
