### ISSUE TITLE
Error when setting Managed Hives Per Acre to null

### ISSUE THREAD

**Issue by arottersman** [project-icp/bee-pollinator-app#166]
Currently you can delete the contents of the managed hives per acre input:
![screen shot 2017-02-17 at 10 41 22 am](https://cloud.githubusercontent.com/assets/7633670/23071825/a557d5a2-f4fd-11e6-93e6-65882c3565cf.png)

Then on blur this causes the modeling job to fail, and the compare view graph to be blank with the hives/acre as `NaN`:
![screen shot 2017-02-17 at 10 38 17 am](https://cloud.githubusercontent.com/assets/7633670/23071944/0addfbc2-f4fe-11e6-96dc-ea364bb72a22.png)

**Comment by rajadain** [comment]
What would be _more_ correct? Setting the value to 0, or to what it previously was before clearing it, if a user erases it? I'm leaning more towards the latter /cc @ajrobbins

**Comment by ajrobbins** [comment]
If the user was trying to erase it, I think it should reset to 0.

**Comment by rajadain** [comment]
I was thinking that if the user wants to set it to 0, they can manually do so. If, on the other hand, they accidentally erase it, then the new value (0 in case we do that) will be saved to the project immediately, and with no undo option, the old value will be lost.

Setting it to the old value ensures there are no accidents, and if they want to make it 0 they can do so manually.
