### ISSUE TITLE
Use client supplied GA keys

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#170]
The app is currently associated with incorrect Google Analytics, update the production settings with a new key.

@ajrobbins this is mostly for you to reach out and have them set up an account and also give us access to it.  We need the `UA-*` key and it should be (for now) associated with the `https://pollinator-modeling-app.azavea.com` domain, though the production one to come.

**Comment by ajrobbins** [comment]
Oooh I get a card! Fun! Will reach out.

**Comment by mmcfarland** [comment]
We've still go to update the value, but we've already got a spot for it.

**Comment by ajrobbins** [comment]
key is `UA-92733102-1`

**Comment by rajadain** [comment]
@ajrobbins In case you'd like to do this yourself, it's a simple change to this line: https://github.com/project-icp/bee-pollinator-app/blob/d9ab5a631b9a87e5db75bbf969bf969995a9e8b9/src/icp/icp/settings/production.py#L111

**Comment by ajrobbins** [comment]
The client confirmed that GA is running and showing usage statistics.
