### ISSUE TITLE
Send Project AoI and Enhancement Polygons

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#175]
The bees folks will be testing our implementation of the model. They'll send us a project/scenario URL, and we should send them the polygons for project AOI and each enhancement. I'm checking on their desired format.

**Comment by ajrobbins** [comment]
Project/scenario info to send:

>User name: taylor.ricketts@gmail.com
>Project: AAAS Demo Project
>“Current Conditions” and “Restore Middle” Scenarios (the second scenario – you can ignore the first).
 
>Insu asks that you clip out the raster data with a buffer of 5km around the site boundary.  I did not update the CDL with any land cover overrides.  The farm contains two crop types and a single polygon in the scenario.

**Comment by ajrobbins** [comment]
GeoTIF format

**Comment by rajadain** [comment]
Area of Interest JSON: [175-area-of-interest.json.txt](https://github.com/project-icp/bee-pollinator-app/files/906802/175-area-of-interest.json.txt)

Modifications JSON: [175-restore-middle-modifications.json.txt](https://github.com/project-icp/bee-pollinator-app/files/906804/175-restore-middle-modifications.json.txt)

**Comment by rajadain** [comment]
Final CDL clipped to 5 km buffer of above AoI is available here: https://drive.google.com/file/d/0BxAxZX0ETxVoQllqUmZsM256Yms/view?usp=sharing (public link)

### Process

 1. Using the project and scenario names above, I found the project in the staging database. I copied the Area of Interest using an SQL query:

    ```sql
    SELECT ST_AsGeoJSON(area_of_interest) FROM modeling_project WHERE id = 18;
    ```

 2. I also made the project public, and it is now accessible here: https://pollinator-modeling-app.azavea.com/project/18/scenario/36
 3. I copied the modifications attached above similarly:

    ```sql
    SELECT modifications FROM modeling_scenario WHERE id = 36;
    ```

 4. I downloaded the latest CDL raster from S3
 5. I imported the CDL raster [EPSG:5070] into QGIS
 6. Imported the Area of Interest [EPSG:4326] into QGIS
 7. I exported the Area of Interest into EPSG:5070 so I could do a buffer in meters (units in 4326 are degrees, but 5070 has meters)
 8. I imported [`aoi-5070.geojson`](https://github.com/project-icp/bee-pollinator-app/files/906967/aoi-5070.geojson.txt) into QGIS, and added a buffer of 5000 meters with 25 segments for a smooth circle.
 9. I exported this buffer into a file [`aoi-5070-buffer.geojson`](https://github.com/project-icp/bee-pollinator-app/files/906969/aoi-5070-buffer.geojson.txt) and re-imported it into QGIS
 10. I then ran a Clipper tool to try and clip the raster, but it was very slow. So I copied the command and added a couple of tweaks in the end:

         gdalwarp -q -cutline aoi-5070-buffer.geojson -tr 30.0 30.0 -of GTiff cdl_reclass_lzw_5070.tif 175-aoi-5km-buffer-clipped.tif -co COMPRESS=LZW --config GDAL_CACHEMAX 8192 -multi

 11. I imported the final `175-aoi-5km-buffer-clipped.tif` into QGIS to make sure it aligned well and looked identical to the existing raster
 12. I uploaded the `175-aoi-5km-buffer-clipped.tif` (63 MB) to Google Drive.

**Comment by rajadain** [comment]
Ah, I was missing `-crop_to_cutline` parameter, which limits the resulting GeoTIFF to the extent of the mask. The resulting file is 38 KB, and is available here: [175-aoi-5km-buffer-clipped-cropped-compressed.tif.zip](https://github.com/project-icp/bee-pollinator-app/files/911202/175-aoi-5km-buffer-clipped-cropped-compressed.tif.zip)

**Comment by rajadain** [comment]
Final output files here: https://drive.google.com/drive/folders/0BxAxZX0ETxVobTdCNUttWVhYZ1E

**Comment by ajrobbins** [comment]
Original project AoI with mod:
![screen shot 2017-04-10 at 3 51 33 pm](https://cloud.githubusercontent.com/assets/12868342/24879675/a29ddbf0-1e05-11e7-8949-68324d60d30c.png)

@rajadain's exported AoI and mod polygons:
![screen shot 2017-04-10 at 3 50 52 pm](https://cloud.githubusercontent.com/assets/12868342/24879703/b28517c2-1e05-11e7-8af3-bd62360a716c.png)

With buffer:
![screen shot 2017-04-10 at 3 52 44 pm](https://cloud.githubusercontent.com/assets/12868342/24879735/ca4f7b68-1e05-11e7-8d31-45d322aa37f1.png)

LGTM.

**Comment by caseycesari** [comment]
LGTM as well.

**Comment by rajadain** [comment]
Thanks for taking a look!

**Comment by mmcfarland** [comment]
I followed up with an intermediate output of the "abundance" layer.  I applied this diff to save off a tiff file for what is otherwise just an array:

```diff
diff --git a/src/icp/pollinator/src/pollinator/crop_yield.py b/src/icp/pollinator/src/pollinator/crop_yield.py
index 91482e5..0f3cc09 100644
--- a/src/icp/pollinator/src/pollinator/crop_yield.py
+++ b/src/icp/pollinator/src/pollinator/crop_yield.py
@@ -218,11 +218,24 @@ def calculate(bee_shed_geom, field_geom, modifications, managed_hives,
     Calculate the change in specific crop yield due to bee abundance
     """
     # Read in the crop raster clipped to the bee shed geometry
-    cdl, affine = extract(bee_shed_geom, raster_path, modifications)
+    cdl, affine, w, meta = extract(bee_shed_geom, raster_path, modifications)
 
     # Determine pollinator abundance across the entire area
     area_abundance = calc_abundance(cdl)
 
+    import rasterio
+    meta.update({
+        'height': w[0][1] - w[0][0],
+        'width': w[1][1] - w[1][0],
+        'driver': 'GTiff',
+        'transform': affine,
+        'dtype': 'float32'
+        })
+    print(meta)
+
+    with rasterio.open('./abundance.tif', 'w', **meta) as out:
+        out.write(area_abundance, indexes=1)
+
     # Vectorize the yield function to allow paired element position input
     # from the CDL, area abundance raster, plus user input and system config
     total_yield = np.vectorize(yield_calc, otypes=[np.float16],
diff --git a/src/icp/pollinator/src/pollinator/raster_ops/__init__.py b/src/icp/pollinator/src/pollinator/raster_ops/__init__.py
index a06f626..930471b 100644
--- a/src/icp/pollinator/src/pollinator/raster_ops/__init__.py
+++ b/src/icp/pollinator/src/pollinator/raster_ops/__init__.py
@@ -59,7 +59,7 @@ def extract(geom, raster_path, mods=None, all_touched=True):
                 all_touched=all_touched,
             )
 
-    return geometry_mask(geom, data, affine, all_touched), affine
+    return geometry_mask(geom, data, affine, all_touched), affine, window, src.meta
 
 
 def geometry_mask(geom, data, affine, all_touched=True):

```

Then ran these SQL statements locally to add the AoI/modification to my local project (Ids are specific to my db)

```sql
update modeling_project set area_of_interest = ST_SetSRID(ST_GeomFromText('MULTIPOLYGON (((-121.599597930908 39.1012750759944, -121.60062789917 39.1020577085149, -121.600949764252 39.103106755499, -121.600756645203 39.1046719711824, -121.600713729858 39.105720979263, -121.600799560547 39.108251855124, -121.600863933563 39.109084360215, -121.588804721832 39.109200910143, -121.58848285675 39.1045720648367, -121.588611602783 39.1031567097279, -121.588718891144 39.1028569838235, -121.589534282684 39.102840332347, -121.591165065765 39.1026571658459, -121.592581272125 39.1020077535072, -121.594212055206 39.1006423029236, -121.595199108124 39.09990961122, -121.596572399139 39.0997930459288, -121.597816944122 39.1004091745712, -121.5989112854 39.1007921707432, -121.599597930908 39.1012750759944)))'), 4326) where id=24;

update modeling_scenario set modifications = '{"name":"conservation_practice","isCurrentConditions":false,"area":13.584295335108903,"effectiveUnits":"acres","value":"wildflower_late","summary":"Grouping of residential homes on a development site in order to use the extra land as open space, recreation or agriculture.","shape":{"geometry":{"type":"Polygon","coordinates":[[[-121.59775257110596,39.10553782024686],[-121.59770965576172,39.10648691181033],[-121.59195899963379,39.10660346603356],[-121.59195899963379,39.10557112192156],[-121.59775257110596,39.10553782024686]]]},"type":"Feature","properties":{}},"effectiveShape":{"geometry":{"type":"Polygon","coordinates":[[[-121.59775257110596,39.10553782024686],[-121.59770965576172,39.10648691181033],[-121.59195899963379,39.10660346603356],[-121.59195899963379,39.10557112192156],[-121.59775257110596,39.10553782024686]]]},"type":"Feature","properties":{}},"effectiveArea":13.584295335108903,"units":"acres","cdlId":61,"type":""}' where id=56;

```
