### ISSUE TITLE
Compare graph overlaps text below

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#179]
On compare page:
![screen shot 2017-04-20 at 11 11 00 am](https://cloud.githubusercontent.com/assets/12868342/25238000/2c513eee-25ba-11e7-8eac-68c3e1107b61.png)

**Comment by arottersman** [comment]
What should happen if the view is too short for the modifications to show at all?

![screen shot 2017-04-25 at 5 06 25 pm](https://cloud.githubusercontent.com/assets/7633670/25407785/a83c6f24-29d9-11e7-9cec-3c2812b39132.png)

I was thinking the whole panel could scroll:

![ibwplwclud](https://cloud.githubusercontent.com/assets/7633670/25407847/f0703956-29d9-11e7-911f-4446924a2925.gif)

**Comment by ajrobbins** [comment]
I like the scrolling! @jfrankl ?

**Comment by arottersman** [comment]
@jfrankl — I have a branch with this change if you want to take this behavior out for a test run.
