### ISSUE TITLE
Make entire "Crop Layer" button clickable

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#183]
Currently, you have to click on the eye icon within the Crop Layer button to turn on the CDL overlay. We should make the entire button clickable.

![screen shot 2017-04-20 at 11 19 58 am](https://cloud.githubusercontent.com/assets/12868342/25238454/7d881de0-25bb-11e7-97ba-fae3c41f7328.png)

**Comment by arottersman** [comment]
Shares a point #188
