### ISSUE TITLE
Remove "early" options from Enhancements dropdown and rename

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#188]
Related to https://github.com/project-icp/bee-pollinator-app/issues/187, remove the "early" options from the Enhancements dropdown:
![screen shot 2017-04-20 at 11 37 29 am](https://cloud.githubusercontent.com/assets/12868342/25239344/c13d5d96-25bd-11e7-9cb1-9e8c0104d6dc.png)

Rename the "late" options to the following (and keep colors):
- Wildflower
- Woody
- Wildflower-Woody Mix

We should probably rearrange the dropdown to have three horizontal options, instead of vertical.

**Comment by arottersman** [comment]
Shares a point with #183
