### ISSUE TITLE
Start UI Workflow

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#19]
We'll be using @jfankl wireframes to start implementing the UI workflow.  Review the wireframes and generate tasks for individual tasks.

**Comment by ajrobbins** [comment]
[2016_10_27_bee-pollinator_v1.pdf](https://github.com/project-icp/bee-pollinator-app/files/576074/2016_10_27_bee-pollinator_v1.pdf)

**Comment by rajadain** [comment]
-1 to #20

**Comment by rajadain** [comment]
-2 to #21

**Comment by rajadain** [comment]
-2 for #22

**Comment by rajadain** [comment]
-1 for #23

**Comment by rajadain** [comment]
-1 for #24

**Comment by rajadain** [comment]
-1 to #25
