### ISSUE TITLE
Add total acreage per crop to Compare page

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#195]
Compare page currently allows the user to select each crop individually for comparison, but doesn't show total acreage for the crop:

![screen shot 2017-04-20 at 12 01 49 pm](https://cloud.githubusercontent.com/assets/12868342/25240592/3ba4bdce-25c1-11e7-964e-be7d0a21a527.png)

**Comment by mmcfarland** [comment]
Duplicate of #153
