### ISSUE TITLE
Size not set on custom map controls in mobile firefox

### ISSUE THREAD

**Issue by arottersman** [project-icp/bee-pollinator-app#200]
In firefox, go to `about:config` and set `dom.w3c_touch_events.enabled` to `1`

Crop layer and basemap controls look like this:
<img width="174" alt="screen shot 2017-04-25 at 5 18 46 pm" src="https://cloud.githubusercontent.com/assets/7633670/25408886/b3cf4f2e-29dd-11e7-9b3a-011abe922c06.png">

**Comment by rajadain** [comment]
Shares a point with #188
