### ISSUE TITLE
Update map to match wireframe

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#21]
- [ ] The draw outline color should be the same `$brand-primary` yellow
 - [ ] The zoom and full-screen map controls go to the bottom right and are now horizontally arranged
 - [ ] Intstead of a complex layer selector, there are two simple buttons to switch between? or toggle? layers
 - [ ] Search remains on the top left, but all other "Draw" and "Reset" buttons are removed

Example:

![image](https://cloud.githubusercontent.com/assets/1430060/20072121/3015e14c-a4f5-11e6-906f-92e4085fd60e.png)

Full wireframes: https://github.com/project-icp/bee-pollinator-app/files/576074/2016_10_27_bee-pollinator_v1.pdf

**Comment by ajrobbins** [comment]
>there are two simple buttons two switch between? or toggle? layers
@jfrankl can you clarify?

**Comment by jtarricone** [comment]
Does the app start in "draw" mode, given that the draw controls have been removed in the design? If so, should that behavior be implemented with the rest of these changes?

**Comment by jtarricone** [comment]
@jfrankl is there a stylesheet or reference for the color palette?

**Comment by rajadain** [comment]
From @jfrankl:

 * The first, bottom-left button will toggle between Satellite and Streets.
 * The second button will toggle an overlay layer

Also, the color palette should be updated as part of #20. @arottersman had the idea of color dropping from the wireframes, so once those are in the drawing color here should update automatically.
