### ISSUE TITLE
Add `overflow-x: hidden` back to compare column

### ISSUE THREAD

**Issue by arottersman** [project-icp/bee-pollinator-app#211]
<img width="318" alt="screen shot 2017-05-04 at 2 12 52 pm" src="https://cloud.githubusercontent.com/assets/7633670/25719441/774683fa-30d7-11e7-91a2-8856f46dbc0c.png">

See #204

**Comment by mmcfarland** [comment]
Shares a point with #202

**Comment by mmcfarland** [comment]
Resolved via https://github.com/project-icp/bee-pollinator-app/pull/216
