### ISSUE TITLE
Add site tour

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#217]
After evaluation, we've decided to use one of these two site tour libraries:
http://linkedin.github.io/hopscotch/
http://github.hubspot.com/shepherd/docs/welcome/

Jeff and I have a slight preference for hopscotch, because we don't want an overlay over the other site elements when one is highlighted for the tour. Pick the one that looks like the easiest to implement, however.

Here is a Marvel link with the site tour points and text (Click the comments button in the bottom left to see): https://marvelapp.com/h3g8796/screen/28035487

**Comment by arottersman** [comment]
@ajrobbins/@jfrankl The tour spans three views: the initial crop map model page, the model page on the new scenario tab, and the compare view. When you click "next" on the last section of the initial crop map part of the tour, should it automatically take you to the new scenario tab? Or should the tour wait until the user has navigated of their own accord?

**Comment by jfrankl** [comment]
The tour should wait until the user has navigated to the next view.

@ajrobbins could you please confirm that this is what we discussed?

**Comment by ajrobbins** [comment]
@jfrankl @arottersman yes, I believe this is what we discussed and it makes sense to me.
