### ISSUE TITLE
Final text changes

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#221]
### Landing page
- [x] Change subheader text paragraph to highlighted text, change numbered steps, and change "Quick start guide" to "Help page":

![screen shot 2017-05-16 at 9 42 32 am](https://cloud.githubusercontent.com/assets/12868342/26108972/04f8f0aa-3a1c-11e7-8cf6-a67977d2e992.png)

### Select field or farm of interest page
- [x] Additional text in yellow:
![screen shot 2017-05-16 at 9 43 48 am](https://cloud.githubusercontent.com/assets/12868342/26109019/33821744-3a1c-11e7-9870-97ab0ee6a148.png)

### Modeling page, if No Data Available
[draw an AoI where there's no cropland]
![no_crops](https://cloud.githubusercontent.com/assets/12868342/26003165/ef813562-36ff-11e7-8a47-880fd90f262b.png)

- [x] Add text that says “or select new area” so that the new text says ”Adjust the Land Cover on this field or select new area to see yield results”

### Modeling page
- [x] _Fix help text for Wildflower-Woody mix in enhancements dropdown:_
![screen shot 2017-05-12 at 10 50 53 am](https://cloud.githubusercontent.com/assets/12868342/26003534/f6bad4f4-3700-11e7-9491-20bcb47d3da6.png)

_Yield graph:_
- [x] Change y-axis of yield figure from “Relative yield” to “% of maximum yield”

- [x] _Yield explanation text, edits in yellow:_
![screen shot 2017-05-16 at 9 57 45 am](https://cloud.githubusercontent.com/assets/12868342/26109759/32408f58-3a1e-11e7-914d-330405cbbd5a.png)

### Compare page
- [x] Change “Navigate Scenarios” in bottom left hand side of page to “Go Back” 

### Multiple places
- [x] Chance "Enhancements" to "Pollinator Plantings" on model page and compare page

**Comment by ajrobbins** [comment]
Blocked until we get final edits from client this week.

**Comment by ajrobbins** [comment]
Final edits received! Unblocked now.

**Comment by arottersman** [comment]
For the landing page, the list item: `1. Zoom in to your farm using the map on the left` is also new, but not highlighted. Should I put it in? Also the directions refer to 4 steps, but with the "Zoom in" step, there would be 5.

**Comment by ajrobbins** [comment]
@arottersman Yes please add that list item. Good catch! Can you:
- change 4 to 5 steps
- delete pollinator habitat and honey bee rates from item 3, so it just says "e.g. crops"

**Comment by ajrobbins** [comment]
Final final edits:
- in landing page list item 3 should just read "update the current crop map"
- Change "CURRENT CONDITIONS" tab to "CURRENT CROP MAP" in modeling page tab and compare page
- In the popup that appears when you click a drawn enhancement: "habitat enhancements" --> "pollinator plantings"
- Under the “crops with cover crop” drop down menu change “Blueberry with Cover Crop” to “Blueberry With Cover Crop”
- Yield explanation text on results change - additional edits in green:
![screen shot 2017-05-18 at 9 06 29 am](https://cloud.githubusercontent.com/assets/12868342/26203460/604bc2be-3ba9-11e7-8544-555a537fd2db.png)
