### ISSUE TITLE
Release to production

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#227]
Release is scheduled for June 28th. Punchlist of remaining items:
- [x] Final text changes #230 
~- [ ]  Site tour implementation~
- [x] bug fixes #229 
- [x] Client to decide on production domain by 6/14 at latest
- [x] Create prod AWS setup

**Comment by hectcastro** [comment]
Is this something we should plan for in the next sprint (starts later today)?

**Comment by ajrobbins** [comment]
@hectcastro No, release is scheduled for late June (aiming for June 28th) - see original comment.

**Comment by mmcfarland** [comment]
> No, release is scheduled for late June


We may be able to start on setting up the production account prior to the domain or release date to give ourselves a little more runway and spread the tasks out over the next two sprints, if that's a planning benefit to ops.

I'd prefer not to wait until the last sprint before release to do some basic smoke testing & instance sizing assessment on the app in the production environment.

**Comment by hectcastro** [comment]
The production environment is setup at https://pollinator-modeling-app.azavea.com/, which puts the staging environment at https://staging.pollinator-modeling-app.azavea.com/. When the update production domain is made available, we'll have to:

- [ ] Create Route 53 hosted zones for it and update the hosted zone references in `default.yml`.
- [ ] Request new certificates for it (approval from the domain registrar owner)
- [ ] Update the email configuration in Django and SES to make use of the new domain for outbound email

**Comment by ajrobbins** [comment]
@hectcastro Based on our recent back-and-forth with the client, I'm pushing back the anticipated date of the release to the week of 7/3. Wanted to let you know for sprint planning purposes. We are still supposed to have the prod domain by mid-June.

**Comment by ajrobbins** [comment]
Update: the domain will be www.pollinationmapper.org. I am working to get connected to the IT person (at Michigan State U) who will configure the DNS.

Production release has been pushed to week of 7/24 (wednesday? whatever works for ops), since we got amendment funding that will enable another sprint or two of work.

**Comment by ajrobbins** [comment]
@hectcastro Now that we have the domain, www.pollinationmapper.org, are we ready for the steps you detailed here https://github.com/project-icp/bee-pollinator-app/issues/227#issuecomment-306259373?

**Comment by hectcastro** [comment]
`NS` records for the hosted zone are:

```
ns-590.awsdns-09.net.
ns-1483.awsdns-57.org.
ns-1978.awsdns-55.co.uk.
ns-490.awsdns-61.com.
```

The certificate approval emails sent to the following email addresses:

```
duynslag@msu.edu
postmaster@pollinationmapper.org
admin@pollinationmapper.org
hostmaster@pollinationmapper.org
webmaster@pollinationmapper.org
administrator@pollinationmapper.org
```

**Comment by ajrobbins** [comment]
@hectcastro Can you reissue the certificate requests?

**Comment by hectcastro** [comment]
Done.

**Comment by ajrobbins** [comment]
Emails have been approved, according to the client.
