### ISSUE TITLE
Migrate painted tiles to Datahub AWS account

### ISSUE THREAD

**Issue by hectcastro** [project-icp/bee-pollinator-app#233]
Currently, the  `s3://com.azavea.datahub.tms/cdl-reclass/` path inside of the GeoTrellis AWS account contains all of the painted tiles. This task is to migrate them to the Datahub AWS account so that they're served via the `{s}.tiles.azavea.com` CDN.

**Comment by ajrobbins** [comment]
Note: Please bill this time to R&D, not bees.
