### ISSUE TITLE
Get corrected tiles to staging

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#234]
Use new tiles on staging. Current URL: s3://com.azavea.datahub.tms/cdl-reclass/. This will change in the future (https://github.com/project-icp/bee-pollinator-app/issues/233) but we can make another change then.

Note: please bill this time to R&D.

**Comment by hectcastro** [comment]
Should be able to use `https://{s}.tiles.azavea.com/cdl-reclass/{z}/{x}/{y}.png`. Things are populating. Might be some holes for zoom levels 12 and up for a few more hours.
