### ISSUE TITLE
Update hive density information

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#236]
Update the hive density table (located here: bee-pollinator-app/src/icp/pollinator/src/pollinator/data/cdl_data.csv) with this csv data (remove .txt):

[cdl_data_6_15_17.csv.txt](https://github.com/project-icp/bee-pollinator-app/files/1078687/cdl_data_6_15_17.csv.txt)

This changes background honey bee stocking rate data from hives/hectare to hives/acre

**Comment by mmcfarland** [comment]
Note that after changing this base csv, the grouped csv needs to be regenerated and checked into the model dir.  Since no new rows were added (presumably), that should be the extent of the process that needs to be run (i.e., the CDL doesn't need to be regenerated)
