### ISSUE TITLE
Update "help page" link on landing page

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#249]
Help page link currently opens in same tab:

![screen shot 2017-07-12 at 10 23 49 am](https://user-images.githubusercontent.com/12868342/28122467-46baa1bc-66ec-11e7-9426-438af593d272.png)

Should open in new tab.

Also, help link URL will be changing before the release, likely to a subdirectory of pollinationmapper.org.

**Comment by arottersman** [comment]
Shares a point with #225

**Comment by ajrobbins** [comment]
Just checked with ICP - we can just use pollinationmapper.org to replace the ICP page help links.
