### ISSUE TITLE
New Modals

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#25]
There may be a new user workflow overall, which necessitates some new modals. It may be beneficial to map out what that workflow looks like, in addition to updating the modals themselves:

![image](https://cloud.githubusercontent.com/assets/1430060/20074697/5a62a69c-a4ff-11e6-802f-d71cbb2472c5.png)

![image](https://cloud.githubusercontent.com/assets/1430060/20074708/6567e21e-a4ff-11e6-830a-94195e3532c0.png)

ps I'm not sure if the white-on-yellow text in the primary button has enough contrast. We may consider using black on yellow instead.

**Comment by arottersman** [comment]
Is there a way to leave the "Model View" besides the browser's back button/closing the browser  tab?

**Comment by rajadain** [comment]
-1 to #23

**Comment by rajadain** [comment]
Closing in favor of #24.
