### ISSUE TITLE
Yellow text should be teal in Compare view modification list

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#251]
In the Compare view mods list, the area figure is still in the yellow which we changed to a teal color elsewhere in the app in https://github.com/project-icp/bee-pollinator-app/pull/238:

![screen shot 2017-07-12 at 10 43 35 am](https://user-images.githubusercontent.com/12868342/28123506-1b3155ba-66ef-11e7-9251-1ace8021ca3c.png)

**Comment by arottersman** [comment]
The teal color is actually `Yuba Blue` https://github.com/project-icp/bee-pollinator-app/blob/develop/src/icp/sass/utils/_variables.scss#L25

**Comment by arottersman** [comment]
Shares a point with #225
