### ISSUE TITLE
Text changes for release

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#257]

**Comment by ajrobbins** [comment]
Waiting for final text edits from ICP team.

**Comment by katharinaxerces** [comment]
@ajrobbins 
-Home page: (1) top left; (2) side bar text: change sentence starting paragraph from "Learn how to integrate managed and wild pollination on your farm in five simple steps using the Pollination Mapper tool:" to  "Learn how to integrate managed and wild pollination on your farm in five simple steps using the Pollination Mapper BETA tool:"

-Project page: under "Pollinator Plantings" change descriptive text for "Woody" from "Flowering shrub and tree planting designed to provide bees with pollen, nectar, and ground and tunnel nesting sites." to "Flowering shrub and tree planting, such as hedgerows or riparian plantings, designed to provide bees with pollen, nectar, and ground and tunnel nesting sites." 

-Project page: under "Pollinator Plantings" change descriptive text for "Wildflower-Woody Mix" from "Wildflower, flowering shrub, and tree planting designed to provide bees with pollen, nectar, and ground and tunnel nesting sites." to "Wildflower, flowering shrub, and tree planting, such as a hedgerow with a wildflower understory, designed to provide bees with pollen, nectar, and ground and tunnel nesting sites."

-Login pop-up: Change "Pollination Mapper" to "Pollination Mapper BETA"

**Comment by ajrobbins** [comment]
Thanks @katharinaxerces.

Also adding this one, reported by Taylor:

For the text under the yield graph - add a comma after "fruit" in the phrase "how much the crop is dependent on pollination to produce fruit" (Second sentence).

**Comment by ajrobbins** [comment]
Still waiting on potential text edits for the site tour, though.

**Comment by katharinaxerces** [comment]
@ajrobbins 

I looked through the site tour two things:
1. I couldn't read the text for the login prompt because it was blocked by the "compare" button. I just added that issue to Github - you should have been notified

2. For the "go back" prompt at the end of the comparison page, change text from "Click here to return to the modeling view." to "Click here to return to the scenario tab."

**Comment by ajrobbins** [comment]
Thanks, @katharinaxerces . This issue now has all of the text changes for the release, so we'll go ahead and implement them.
