### ISSUE TITLE
Add option to minimize "crop layer legend"

### ISSUE THREAD

**Issue by katharinaxerces** [project-icp/bee-pollinator-app#261]
@ajrobbins 
Currently you can't minimize the crop layer legend if it's "on". This causes problems when trying to outline a field covered by the legend.

Add an option to minimize the "crop layer legend" after turning the crop layer "on"

**Comment by ajrobbins** [comment]
@katharinaxerces You actually can collapse the crop layer legend by clicking the little list icon at the right end of the layer bar:

![screen shot 2017-07-14 at 4 56 00 pm](https://user-images.githubusercontent.com/12868342/28230547-7248b9ac-68b5-11e7-806d-d3d7cf5202ff.png)

**Comment by katharinaxerces** [comment]
Thanks for the heads up. I'll add this to the help guide.
k
