### ISSUE TITLE
Create a host record for pollinationmapper.org landing page

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#264]
The ICP team is creating a landing page at pollinationmapper.org. They're requesting that we add a record at 35.8.12.67, where they have it hosted.

**Comment by ajrobbins** [comment]
From client:
>Is there any way they can create a DNS record so that website comes up with the www also?  So www.pollinationmapper.org?  I see it does come up at pollinationmapper.org, but not www.pollinationmapper.org
 
Hostname: www.pollinationmapper.org
IP address is:  35.8.12.67

**Comment by hectcastro** [comment]
Done. Site is tight.

**Comment by ajrobbins** [comment]
Thank you!!

**Comment by mmcfarland** [comment]
`CNAME` and `A` records were updated to reflect new hosting and DNS for the non-app website.

```
45.60.149.216
45.60.169.216
```
