### ISSUE TITLE
move "login" site tour prompt to front

### ISSUE THREAD

**Issue by katharinaxerces** [project-icp/bee-pollinator-app#270]
@ajrobbins 
Right now the "compare" link sits on top of the login prompt at the end of the scenerio page site tour 

![login](https://user-images.githubusercontent.com/30185134/28548584-9abc098a-7089-11e7-9236-633578e43e9b.jpg)

**Comment by ajrobbins** [comment]
Good catch! I've added this bug to our queue to fix.

**Comment by katharinaxerces** [comment]
@ajrobbins Hey Arianna, can you confirm that this will be added to the production site when it's compelted?

**Comment by ajrobbins** [comment]
@katharinaxerces It's on the production site now (may need a hard refresh to see it).
