### ISSUE TITLE
#10 Exception: Unable to receive a PONG from any workers

### ISSUE THREAD

**Issue by arottersman** [project-icp/bee-pollinator-app#276]
https://rollbar.com/ProjectICP/Bee-Pollinator/items/10/?item_page=0&item_count=100&#traceback

from @mmcfarland 
> The previous time this got expressed was that the client failed to connect to redis, the log was filled with failures.  I'm not sure if a connection is somehow getting cached and stale or what.

> The band-aid fix is to add a health check that determines the ability to to connect to redis and cull if not.

> The real fix is to probably remove the custom worker choosing that we inherited from MMW, since we shoudl be able to submit jobs "normally", meaning we don't have SJS to make workarounds for.

**Comment by mmcfarland** [comment]
[Here are the logs](https://github.com/project-icp/bee-pollinator-app/files/1240254/celery-worker-logs.zip) from the celery process when the most recent failure occurred.  You'll notice that there are `missed heartbeat` errors, but also that there are similar errors that seem to have self recovered.  It may be that there have been transient connectivity errors, but we're only notified when it coincides with a user trying to actually run a model.

A brief search showed [a thread](https://github.com/celery/celery/issues/2296) that speculated all sorts of causes for this generic error, including low memory.  Here is a graph of free memory for production workers over the last few months.  It does seem to dip regularly, but it's unclear if the errors are related.

![screenshot from 2017-08-21 17 52 13](https://user-images.githubusercontent.com/1014341/29540161-1952ced8-869b-11e7-8518-f773765b414c.png)

![recent-icp-workers](https://user-images.githubusercontent.com/1014341/29540154-13a98e5e-869b-11e7-960f-e690471d5fe5.png)
