### ISSUE TITLE
Bring down staging environment

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#279]
We are no longer actively developing the pollination modeling application, so we should take down the staging environment to save on those resources.

**Comment by hectcastro** [comment]
Is this a situation where we are planning to take it down for good, or we want to partially take it down to support future updates/maintenance?

**Comment by ajrobbins** [comment]
Our main goal is to stop them from being charged for it. Can we achieve that with a partial takedown? If not, I say full takedown. We have no support contract or work in the pipeline for this project.

**Comment by hectcastro** [comment]
Full puts us in a situation where it would be 3-5 points to get things operational again. Partial is probably less than a 1, but will continue to incur a subset of the infrastructure costs.

**Comment by ajrobbins** [comment]
+1 to full take down, thanks for the explanation! We can include time to get it back up and running into the budget for a future contract.
