### ISSUE TITLE
Discuss Bees Front-End 2.0

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#284]

**Comment by fungjj92** [comment]
Draft at https://github.com/project-icp/bee-pollinator-app/blob/jf/phase2-adr/doc/Phase%202/000_project_architecture_adr.md @rajadain 

While we talked about it in the meeting, I excluded discussion of how versions of client uploaded data would be signified to map click entries because that discussion seemed premature for now.

**Comment by rajadain** [comment]
Thanks for putting that together! Since I can't comment on the file directly, I'm posting some initial thoughts here:

---

> There will be dedicated user accounts as well as the ability to sign in with credentials from app.pollinationmapper.org.

My impression was that each app will have its own user accounts, and they will be separate. If a user already has an account in 1, they'll have to make a new one for 2. We should confirm that with @mmcfarland.

> where will 2 live?

"live" is ambiguous here, as it refers both to the deployment environment and the repo. It is valuable to differentiate the two and talk about their separation from 1's repo and deployment individually.

> If separate (opposite, for combined)

Consider making this into a table. That would be easier to read than flipping a list in one's mind.

> The crux of the decision comes down to auth.

Consider moving this paragraph to the previous section. By the time we get to the "Decision" part of the ADR, all the influencing factors should have been discussed.

> syncing user tables

This was never an issue, since 2 isn't going to have its own back-end or its own user tables. Whether we developed 2 as a separate front-end project or a sibling Django template, we were always going to use the existing user table for user management. The one tweak we'll need to make to the existing table (as mentioned in the planning meeting) is to add a column to the user table which indicates to which app the user signed up from.

> Bonus: reduced operations labor.

While it is true that 2 and API will be deployed together, this also means that 2, which will be a simple static front-end app, and significantly simpler to deploy on its own, cannot be deployed without the overhead of also deploying the API.

> there is a certain amount of uniqueness we want to update the API with as we build out 2

I'm not following this very well. By "uniqueness" do you mean custom functions that will be used only in 2 and not 1? Consider rephrasing "certain amount of uniqueness" to "set of custom functionality".

**Comment by fungjj92** [comment]
Thanks for looking promptly. Oof, let me make the branch into a PR so it is easier to work with. I'll copy over your comments.
