### ISSUE TITLE
Beekeepers UI Handoff and Planning

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#292]

**Comment by mmcfarland** [comment]
If `forageRange` was changed from `3` to `5`, would a new entry be added to `scores` after calculation

```json
"forage_spring_5k": {
    "data": 75,
    "error": null
}
```

Such that on subsequent flips of that dropdown, we check and see we already have a value?

**Comment by rajadain** [comment]
Good point, we got confused and thought that the `3k` and `5k` applied only to the forage rasters. In fact, the seasons only apply to forage rasters, but the forage range applies to all rasters. In this case, we may use that as a the first key under `scores`, like this:

```json
{
    "sortBy": "",
    "forageRange": "",
    "apiaries": [
        {
            "name": "",
            "location": {
                "lat": 1.0,
                "lon": 1.0
            },
            "scores": {
                "3k": {
                    "hive_density": {
                        "data": 26,
                        "error": null
                    },
                    "forage_fall": {
                        "data": 45,
                        "error": null
                    },
                    "forage_spring": {
                        "data": 61,
                        "error": null
                    },
                },
                "5k": {
                    "hive_density": {
                        "data": 30,
                        "error": null
                    },
                    "forage_fall": {
                        "data": 49,
                        "error": null
                    },
                    "forage_spring": {
                        "data": 65,
                        "error": null
                    },
                }
            },
            "fetching": false,
            "starred": false,
            "surveyed": false,
        }
    ]
}
```

The API will be queried with a given forage range and those results will be saved the first time. In the future, if the values are already there, they will be shown instantly.

Example:

- Forage Range is set to "3km"
- User makes a point **A** on the map
- Scores for **A** are fetched with a forage range for "3km"
- User switches Forage Range to "5km"
- Scores for **A** are fetched with a forage range for "5km"
- User adds a new point **B** on the map
- Scores for **B** are fetched with a forage range of "5km"
- User switches Forage Range to "3km"
- Scores for **A** with a forage range of "3km" are shown instantly,
  Scores for **B** are fetched with a forage range of "3km"

**Comment by mmcfarland** [comment]
Sounds good.  Additionally, we'll be able to play with the idea of fetching all 3k/5k values at one go depending on performance.

**Comment by rajadain** [comment]
For prop type validation, it may be better for us to go with this structure for `scores`:

```json
"scores": {
    "3k": [
        {
            "name": "hive_density",
            "data": 26,
            "error": null
        },
        {
            "name": "forage_fall",
            "data": 45,
            "error": null
        },
        {
            "name": "forage_spring",
            "data": 61,
            "error": null
        },
    ],
    "5k": [
        {
            "name": "hive_density",
            "data": 30,
            "error": null
        },
        {
            "name": "forage_fall",
            "data": 49,
            "error": null
        },
        {
            "name": "forage_spring",
            "data": 65,
            "error": null
        },
    ]
}
```

So we can have a prop type like:

```js
"scores": shape({
    "3k": arrayOf(Score).isRequired,
    "5k": arrayOf(Score).isRequired
})
```

rather than encoding the raster keys into the prop type (which would make it harder to change them in the future):

```js
"scores": shape({
    "3k": shape({
        "hive_density": Score.isRequired,
        "forage_fall": Score.isRequired,
        "forage_spring": Score.isRequired,
    }),
    "5k": shape({
        "hive_density": Score.isRequired,
        "forage_fall": Score.isRequired,
        "forage_spring": Score.isRequired,
    })
})
```

**Comment by rajadain** [comment]
We should also go with keys that don't start with numbers, like `threeKm` instead of `3k`, so we can use them without quoting.
