### ISSUE TITLE
Add Basemap

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#299]
In the wireframes, the Mapbox Satellite Streets basemap is used:

![image](https://user-images.githubusercontent.com/1430060/47241463-be4e1980-d3b9-11e8-9c6c-c25b207cf7ba.png)

Mapbox basemaps typically require tokens. Should we get the token from the client? Should we use a different basemap?

**Comment by fungjj92** [comment]
Requires #300

**Comment by mmcfarland** [comment]
We had decided to use Esri world imagery (same as Pollinator) but try adding the Carto label layer as a composite as well.
