### ISSUE TITLE
Add Geocoder to Map Component

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#301]
There should be a geocoder on the map as shown in the wireframes:

![image](https://user-images.githubusercontent.com/1430060/47241463-be4e1980-d3b9-11e8-9c6c-c25b207cf7ba.png)

Requires #300

**Comment by fungjj92** [comment]
Requires #300

**Comment by rajadain** [comment]
"Requires" can't be a comment, you have to edit the main description to include it.
