### ISSUE TITLE
Edit Apiary Name in Card

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#303]
As shown here, hovering on an Apiary Card should show a pencil icon near the name:

![image](https://user-images.githubusercontent.com/1430060/47242131-e63e7c80-d3bb-11e8-8691-4891785a8ddf.png)

When it is clicked, the name should become an editable field with a save button:

![image](https://user-images.githubusercontent.com/1430060/47242194-09692c00-d3bc-11e8-8917-e74a30ae5e8a.png)

Requires #302

**Comment by fungjj92** [comment]
Requires #302

**Comment by rajadain** [comment]
Blocked until confirmed by client
