### ISSUE TITLE
Baseline scale for current dataset values

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#313]
Placeholder for value scale.  Anticipate the following changes:
* Additional datasets
* Scale ranges altered
* Scale ranges normalized to a single scale

|Dataset|Low|Med|High
|---|---|---|---
|Spring For| 0 to 0.399|0.400 to 0.5799|0.58 to 1.0
|Summer For|	0 to 0.449|	0.450 to 0.519	|0.52 to 1.0
|Fall For|	        0 to 0.329|	0.330 to 0.399|	0.4 to 1.0
|Insecticide|	0 to 10	|	11 to 499|	        500 to ???

**Comment by fungjj92** [comment]
Not doing baselines feature anymore.
