### ISSUE TITLE
Marker styling should correspond to its apiary card

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#322]
Whereas they are both circles with a matching color and letter. FYI they're not all supposed to be the same color.

<img width="526" alt="screen shot 2018-11-05 at 5 28 51 pm" src="https://user-images.githubusercontent.com/10568752/48030835-4a817000-e120-11e8-8129-d59cdb27a7bc.png">

**Comment by rajadain** [comment]
Closing in favor of #369
