### ISSUE TITLE
Make the "Participate in study" button in the top-right open a Login / Sign Up modal

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#325]
Currently in the app you will see a functionless "Account" button in the top right of the header. First, update that to the purpleish "Participate in study" button. Upon clicking, a modal like that seen below should pop up that can toggle between two forms -- sign up or login.

![image](https://user-images.githubusercontent.com/10568752/48427304-74e1b780-e736-11e8-93eb-a46f68d91d2d.png)

<img width="408" alt="screen shot 2018-12-03 at 11 14 11 am" src="https://user-images.githubusercontent.com/10568752/49386006-a2de6a00-f6ec-11e8-8e6b-8da8bf60dd9a.png">

<img width="212" alt="screen shot 2018-12-03 at 11 14 26 am" src="https://user-images.githubusercontent.com/10568752/49386007-a2de6a00-f6ec-11e8-8abf-198d5d5ad459.png">

**Comment by kellyi** [comment]
In case it helps this is a pretty nice library we've used for modals: https://www.npmjs.com/package/reactjs-popup

There's also react-modal, but I think reactjs-popup has a slightly nicer API.
