### ISSUE TITLE
Geocoder broken on staging

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#353]
Searching for an address results in this error on staging :(

<img width="374" alt="screen shot 2018-12-03 at 11 19 40 am" src="https://user-images.githubusercontent.com/10568752/49386366-62cbb700-f6ed-11e8-8013-483fee35ebc7.png">

**Comment by mmcfarland** [comment]
I think this is the same root cause as #352, and we need to update the authorized origin domains for the esri geocoding service.

**Comment by fungjj92** [comment]
Oh yea I just saw that. Easy change so I updated the domains on ESRI, closing both issues.
