### ISSUE TITLE
Attach User's CSRF token to non-GET requests to Django

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#358]
If you’re logged into the pollination front end, beekeepers requests to the backend will fail with a `403`. The underlying error: `CSRF Failed: CSRF token missing or incorrect.` To fix, user's non-GET requests to the backend should send their CSRF token too. [Revelant Stackoverflow explanation](https://stackoverflow.com/questions/32653518/django-rest-framework-returning-403-response-on-post-put-delete-despite-allowa).

Discovered locally and on staging.

Requires #327

**Comment by rajadain** [comment]
Shares points with #327
