### ISSUE TITLE
Add error state to ApiaryCard

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#359]
Currently if you click outside the range, or if something goes wrong, the spinner spins forever:

![image](https://user-images.githubusercontent.com/1430060/49475279-ca186280-f7e4-11e8-9447-d23c4da255a8.png)

Make it so that an error icon is shown if it fails.

**Comment by fungjj92** [comment]
Extension of #356

**Comment by rajadain** [comment]
Duplicate of #356
