### ISSUE TITLE
Add tooltips to Apiary Card buttons

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#376]
Add tooltips to "Star", "Survey", and "Delete" buttons in an Apiary Card.

**Comment by rajadain** [comment]
Use HTML attribute `title`. Add a single sentence for each.

**Comment by dboyer** [comment]
Star - Use the star feature to remember important apiaries.
Delete - Delete this apiary.
Survey - Click to add this to the list of apiaries needing surveys.

@jfrankl Does this text reflect the purposes these buttons serve?

**Comment by jfrankl** [comment]
Yes, that looks good in terms of the purposes.

One copy recommendation, for what it's worth: I'd remove "Click to" from the survey tooltip, because I think that's implied it will happen when the user clicks the button. Otherwise, looks good to me.
