### ISSUE TITLE
Remove expand/collapse from compare view map images

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#39]
![screen shot 2016-11-11 at 4 25 39 pm](https://cloud.githubusercontent.com/assets/12868342/20231012/ef120186-a82c-11e6-99cf-dc97a099640d.png)

Should look like it does on MMW:

![screen shot 2016-11-11 at 4 36 14 pm](https://cloud.githubusercontent.com/assets/12868342/20231026/02a6010c-a82d-11e6-819b-45883054d17c.png)

**Comment by arottersman** [comment]
Shares a point with https://github.com/project-icp/bee-pollinator-app/pull/41
