### ISSUE TITLE
Sort options in dropdown don't match apiary card

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#391]
Since the forage raster was renamed to floral, there's a mismatch in the front end. I think we should stick to one naming convention and be firm about it.

<img width="464" alt="screen shot 2018-12-20 at 5 05 10 pm" src="https://user-images.githubusercontent.com/10568752/50313461-727f2580-0479-11e9-8f9e-91c19000806b.png">

**Comment by dboyer** [comment]
We should go with Floral, per feedback from Penn State.
