### ISSUE TITLE
Styling pass list

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#393]
A place to accumulate styling issues for the next styling pass.

- [ ] Adding new apiary cards when the sidebar has vertical scroll adds a page scroll for a second
![flashscroll](https://user-images.githubusercontent.com/10568752/50348554-15ca4c00-0507-11e9-8d33-7e3500ab5b32.gif)

- [ ] What marker color should starred & surveyed apiaries get?

- [x] ~~Markers need better styling~~

- [x] Need to add real icons for the check and circle on survey cards, and the user dropdown caret

- [x] the survey view in general

- [x] Survey Detail Dialog in particular

- [x] Long apiary names overflow

- [x] All forms could use some design work, especially aligning labels and checkboxes.

- [x] Sidebar doesn't scroll in Firefox (the whole page scrolls instead):
    ![2019-01-10 11 59 50](https://user-images.githubusercontent.com/1430060/50984291-88f42c00-14cf-11e9-9b7f-47961425f766.gif)

- [x]  Gray highlight around survey links in Chrome 65 and Firefox. See:
![image](https://user-images.githubusercontent.com/10568752/51194973-24afde80-18ba-11e9-8f03-8f88371e3e98.png)

- [ ] Add styling to the "Retry" fetch data request button:
<img width="408" alt="screen shot 2019-01-15 at 5 40 06 pm" src="https://user-images.githubusercontent.com/10568752/51494953-9a1f2180-1d88-11e9-90e4-a18405e4c7c3.png">

**Comment by rajadain** [comment]
Hey @jfrankl it would be great if you could take a look at these issues above. Let us know if we can help / pair / provide context or assistance. Thanks.

**Comment by jfrankl** [comment]
@rajadain sure thing. I'm planning to work on styling cleanup tomorrow and will reply to these issues then.

**Comment by jfrankl** [comment]
For the "Retry" fetch data error, it's possible to have multiple of those accumulate on the screen. It's also not possible to remove them, aside from "Retry" and hoping that works.

![image](https://user-images.githubusercontent.com/1809908/51952565-f9bfa180-2406-11e9-8d40-874c2c3dad13.png)

For now, let's add an "X" button to close these elements.
