### ISSUE TITLE
Prepare 2017 CDL version for use

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#407]
The 2017 CDL needs to be preprocessed so that it can be tiled and incorporated into the original PollinationMapper.

Source
https://www.nass.usda.gov/Research_and_Science/Cropland/Release/index.php

* [x] Acquire raw CDL raster
* [ ] Group & Reclassify according to https://github.com/project-icp/bee-pollinator-app/tree/develop/src/icp/pollinator/src/pollinator/reclass

The follow up work is detailed in #371, #373 and #377

**Comment by rajadain** [comment]
Is the reclassification complete? Can we check the second box?

**Comment by mmcfarland** [comment]
It is.  Reclassified raster can be found in the icp s3 bucket: `icp-cdl-data`
