### ISSUE TITLE
Improve Form Workflow

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#416]
Currently when the user fills out their user form which appears on first login, it just disappears. This can be a bit jarring. ~~Add a prompt or message thanking the user, and introducing the next steps. Need to figure out exactly what should be shown. Talk to designers and PM before proceeding.~~

When a form is filled out, close the modal, then show a modal that says "Form Submitted" and some indication of success ✅. Optionally, the modal should close itself after a few seconds.

**Comment by fungjj92** [comment]
I think this popup can apply for #402 as well, so I'm rolling them into one.
