### ISSUE TITLE
Fix Scenario Switching

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#42]
~~Modifications should only be visible for hypothetical scenarios, not current conditions. Currently they are visible in both.~~

It seems like scenario switching as a whole is broken:

![bee-scenarios-not-switcing](https://cloud.githubusercontent.com/assets/1430060/20272744/d4804332-aa5c-11e6-956e-fc179f2340fb.gif)

**Comment by arottersman** [comment]
This is for the most part fixed in #41 (the tabs didn't have their id's set)

Even with #41, however, the input field will still appear on Current Conditions. Going to add a fix in #36

**Comment by rajadain** [comment]
Great!
