### ISSUE TITLE
Map not displaying in Safari

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#424]
Tested in Safari Version 10.1.2 on a Macbook Air

Map does not appear on staging site. Checked when I was logged in and was not logged in and when I was on the VPN and not on the VPN and saw same result.

![screen shot 2019-01-16 at 9 13 25 am](https://user-images.githubusercontent.com/516764/51254750-b9c0df00-196f-11e9-92c5-ee37a779d7f8.png)

**Comment by fungjj92** [comment]
Hold off

**Comment by fungjj92** [comment]
Verified map visible in safari.
