### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#427]
The main domain is beescape.org with beescape.net and beescape.info also purchased

Requires #432

**Comment by mmcfarland** [comment]
A few questions/statements:

* Currently, the repo is set up for `app.pollinationmapper.org` and `staging.app.pollinationmapper.org`, we'll be adding the additional domain, but routing to the same ELB.  We'll make the app changes necessary to serve the right payload based on the `host` separately.
* Will we be serving from `app.beescape.org` or directly from `beescape.org` (ie, are they repurposing the root domain for project content)? @dboyer 
* This change should be provided for production and staging, based on the answer to the above question.

**Comment by dboyer** [comment]
There will be a landing page at beescape.org so we should be serving from app.beescape.org

**Comment by hectcastro** [comment]
> ...we'll be adding the additional domain, but routing to the same ELB.

Minor detail, but mentioning because it has cost implications. It'll actually be a separate ELB because we need to isolate TLS certificates for HTTPS.

**Comment by hectcastro** [comment]
- Create Route 53 hosted zone for `app.beescape.org` and provide client with `NS` records
- Once managed by Route 53; provision ACM certificate with DNS validation
- Add AWS resources necessary to support an additional domain via CloudFormation

See: https://github.com/WikiWatershed/model-my-watershed/commit/ff67775de5582e377a62e8cd2dab4c54b8d23e32

**Comment by jeancochrane** [comment]
Opened up https://github.com/project-icp/bee-pollinator-app/pull/457 to address the third bullet above (`Add AWS resources...`). Once bullet 2 (`provision ACM certificate`) is done, we can test and review #457.
