### ISSUE TITLE
Hide "Expand" Icon in Compare View

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#44]
The "Expand" or "Hide Sidebar" Leaflet control should not be visible in the Compare View:

![image](https://cloud.githubusercontent.com/assets/1430060/20272873/4e139c80-aa5d-11e6-8dcc-0f9334a0d7c8.png)

**Comment by arottersman** [comment]
Good catch - this is the same as issue #39, and is being addressed in PR #41

**Comment by rajadain** [comment]
Ah thanks. Sorry for the dupe
