### ISSUE TITLE
Add yes/no options to questions on user info form

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#450]
The initial user info form has several yes/no questions with a single checkbox. Can these have either a yes/no dropdown or two yes/no checkboxes?

- Do you relocate your colony?
- Do you manage for Varroa?
- Do you buy queens, nucs or packages?
- Do you use Varroa-resistant queens?
- Do you rear queens?

**Comment by rajadain** [comment]
These were converted to dropdowns:

![image](https://user-images.githubusercontent.com/1430060/54368788-293f0c00-464b-11e9-9ca3-02409a740a10.png)

done in cbeaa2eb.
