### ISSUE TITLE
User loses survey progress if they click outside of modal

### ISSUE THREAD

**Issue by jfrankl** [project-icp/bee-pollinator-app#452]
When filling out a survey, clicking outside of the modal closes the modal. Closing the modal deletes all of the data the user has filled out, which is a usability issue.

The easiest way to fix this would be to disable closing the modal by clicking outside of it and instead having a cancel button to close the survey. An alternative, which I think would take longer to develop, would be to warn the user that they are about to lose their progress.

![image](https://user-images.githubusercontent.com/1809908/51959652-62b51280-2423-11e9-8a31-cf4d6169c066.png)

**Comment by rajadain** [comment]
Fixed by #572.
