### ISSUE TITLE
Add close button to "error fetching apiary data" card

### ISSUE THREAD

**Issue by jfrankl** [project-icp/bee-pollinator-app#453]
For the "Retry" fetch data error, it's possible to have multiple of those accumulate on the screen. It's also not possible to remove them, aside from "Retry" and hoping that works.

![image](https://user-images.githubusercontent.com/1809908/51952565-f9bfa180-2406-11e9-8d40-874c2c3dad13.png)

For now, let's add an "X" button to close these elements and remove the related marker.

**Comment by rajadain** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/1430060/52088433-cd786200-2579-11e9-9ee3-f28d2b5d4574.png)

Close Up:

![image](https://user-images.githubusercontent.com/1430060/52088448-da955100-2579-11e9-97ca-2cb89c8f76fe.png)

**Comment by rajadain** [comment]
I can also replace it with an `X` button if that's a better fit here.

**Comment by jfrankl** [comment]
I think that looks good with the trash icon.

If we have more time in the future, we might want to consider moving "Try again" up to the header and not having the footer part of the card. I don't think that's necessary for now.

![image](https://user-images.githubusercontent.com/1809908/52089165-e97d0300-257b-11e9-89dc-a60b223b8e9d.png)

**Comment by rajadain** [comment]
Thanks. Doesn't look like it can be done without CSS changes, so I'm leaving it as is for now:

![image](https://user-images.githubusercontent.com/1430060/52089343-555f6b80-257c-11e9-911c-d8db5a44ee50.png)
