### ISSUE TITLE
Don't show empty category title in survey

### ISSUE THREAD

**Issue by jfrankl** [project-icp/bee-pollinator-app#455]
In the survey view, if one of the three categories (Response needed, Up to date, This is not in the study) is empty, the heading is displayed with no content under it. That looks odd—let's remove the heading when the section is empty.

![image](https://user-images.githubusercontent.com/1809908/51988229-307ed180-2472-11e9-975f-ae0111620c40.png)

**Comment by fungjj92** [comment]
<img width="573" alt="screen shot 2019-02-01 at 12 22 09 pm" src="https://user-images.githubusercontent.com/10568752/52138777-24367800-261c-11e9-9f9b-0dbb06cfe0dd.png">

UX feels a little strange when categories appear/disappear. I'm suggesting we keep all the headers but have "empty state" text of encouragement/mild shame, see screenshot.

**Comment by jfrankl** [comment]
Great, I like the idea of empty states, I agree it works better.

I have two thoughts about this.

1. Design nitpick: please make sure the empty state text lines up with the headings. They look indented right now.
![image](https://user-images.githubusercontent.com/1809908/52139048-00bffd00-261d-11e9-84c6-cb9906aef0fb.png)

2. Would be good to get @dboyer or other feedback on the copy. I would advise to not use "shame" though and to keep it informative and friendly.

**Comment by dboyer** [comment]
Let's go with:

- None. There are no remaining surveys to complete.
- None. Please help the bees and complete the following surveys.

Would we ever ask for surveys of apiaries that aren't in the study? I don't quite understand the text for the last option.

**Comment by fungjj92** [comment]
Data collection is all optional. I figured that congratulatory text to the user for opting in to collect data for all of their apiaries was in order.
