### ISSUE TITLE
Add monthly survey field and autofill functionality

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#463]
- "Do you have an automated scale associated with this colony?" added as a required question for each colony in the monthly survey
- If the user says yes, they would then be prompted to enter the brand and ID number as a required field
- If they say yes, the entered brand and ID number are autofilled on the following monthly surveys
- Colony name also becomes a field autofilled on the following monthly surveys
- Beekeepers can edit the colony name and brand and ID number for the automated scale if needed

**Comment by rajadain** [comment]
Automated Scale ID field was added in #491.

The colony name and automated scale ID field currently do not autofill, and need to be entered each time.

**Comment by dboyer** [comment]
We do not need to autofill at this time. I've labeled this as an enhancement.

**Comment by rajadain** [comment]
Blocked until confirmed by client
