### ISSUE TITLE
Add Score Information in Popups

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#468]
Use the following table to populate the popup to indicate to the user which bucket their score falls under:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/1430060/52492579-79800580-2b97-11e9-8ca5-b61b6de049a9.png">

![image](https://user-images.githubusercontent.com/1430060/52492688-afbd8500-2b97-11e9-9617-2bc3a4f0602a.png)

Show the entire row for the appropriate type. E.g. if the type is Spring Floral, we show a table of the five stops and scores for Spring Floral.

Optionally, highlight / make prominent their score in the table or popup description.

**Comment by rajadain** [comment]
Client Notes:

> How to read this:
> 
> Anything at the low score or lower is considered “low levels” (40 or less for spring)
>
> Anything at the high score or higher is considered “high levels” (53 or more for spring)
> 
> I think Azavea converted the pesticide index to a 1-100 scale, so the scores should be converted accordingly.
> 
> High is good for floral resources and nesting, BAD for pesticide load.  This may be confusing for people (at least, an assistant prof working with us was confused by this…). Might be good to use some color coding?

**Comment by rajadain** [comment]
@mmcfarland Is it true that we changed the Pesticide scale to 1-100? Or are we just multiplying the values when rendering in the front-end? As far as I can tell we're only multiplying the displayed results with 100, same as for every other indicator:

![image](https://user-images.githubusercontent.com/1430060/52506057-49e2f480-2bbb-11e9-926b-e6e0c12be0c2.png)

![image](https://user-images.githubusercontent.com/1430060/52506094-63843c00-2bbb-11e9-92d2-0c0911e2c796.png)

and haven't rescaled the original values.

**Comment by dboyer** [comment]
@rajadain  Text is:

Spring Floral Quality:
High >53
Low <40

Summer Floral Quality
High >49
Low <44

Fall Floral Resource Quality
High >36
Low <30

Nesting Quality  
High >46 
Low <33

Pesticide 
High Expected Levels >37 
Low Expected Levels <13

**Comment by mmcfarland** [comment]
> and haven't rescaled the original values.

@rajadain Sorry I missed this. That is correct.

**Comment by dboyer** [comment]
@rajadain Penn State confirmed that the remaining sentence of lorem ipsum can just be removed from each of the pop-up boxes. There does not need to be any type of summary sentence in the box.
