### ISSUE TITLE
Deploy to Production (3/18)

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#480]
Target Date: Early March.

- [x] Backup production database
- [x] Run migrations
- [x] Ensure new data available on https://app.pollinationmapper.org/
- [x] Ensure site works correctly on https://app.beescape.org/
- [x] Create accounts for admins #434

**Comment by rbreslow** [comment]
Tentatively scheduled for Tuesday 3/12.

**Comment by dboyer** [comment]
Target date for production launch is March 18

**Comment by rajadain** [comment]
Opening until points are counted in Civic Apps sprint.
