### ISSUE TITLE
Beekeepers Final Text Changes

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#481]
### Update Logo

![beescape2](https://user-images.githubusercontent.com/1430060/53201498-2f187300-35f2-11e9-8de4-a81f203aad44.png)

### Update Text in Score Label Popups

Remove lorem ipsum from the score label popups, and replace the text with directions here: https://github.com/project-icp/bee-pollinator-app/issues/468#issuecomment-465670044

### Text on survey page when user not logged in (waiting on one link)

**Help us see the world as a bee!**
Our goal is to give beekeepers, gardeners, and growers detailed information about the quality of their landscapes for bees, and site-specific recommendations for land and bee management practices. But, to do this, we need your help, so we can have data from many diverse landscapes! If you have a wild bee hotel and would like to participate in our study, please click here. If you are a beekeeper, please follow the link below.

### Home and Methodology links

**Comment by hectcastro** [comment]
From Harland: Make the **Methodology** button in the page header link to http://beescape.org/ (no HTTPS).

**Comment by fungjj92** [comment]
Strange -- wouldn't we rather want:

Home --> http://beescape.org/
Methodology-->http://beescape.org/methodology/

**Comment by hectcastro** [comment]
I think you're right. I misread the original message:

> ... Azavea will make a link on their site  to our Methodology page on beescape.org.  From what I understand there are no other links.

Would be good to confirm with @dboyer. I jotted this down to make sure it didn't get lost in the email thread we're on to sort DNS.

**Comment by dboyer** [comment]
Correct, Home should link to beescape.org and Methodology should link to beescape.org/methodology
