### ISSUE TITLE
Keep staging available 24 hours a day

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#483]
Staging is currently set to be down from 8pm to 8am. We should keep it available at all times now that the beekeepers are testing the site.

**Comment by hectcastro** [comment]
Previously, **Desired Capacity** under the **Scheduled Actions** tab was set to 1 for the first line item and 0 for the second. Now, they are both 1, which should prevent any scheduled scaling actions from messing with the available EC2 instances:

<img width="1221" alt="screen shot 2019-02-27 at 11 57 45 am" src="https://user-images.githubusercontent.com/43639/53508004-f57ab880-3a86-11e9-9049-92c357a4974a.png">

cc: @fungjj92
