### ISSUE TITLE
Hard to find the CDL 

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#485]
Users reported it was challenging to find the CDL and didn't realize they could view it by clicking the stack icon in the lower left of the map. Possible suggestions to make it more visible include a tooltip when hovering over the icon, have the table of values always visible, or add text explaining the CDL somewhere.

Tagging @jfrankl for design feedback on the best way to emphasize this feature.

**Comment by jfrankl** [comment]
I spoke with @dboyer about this. To make the CDL more discoverable, let's add a button that includes a label and image. This will include moving the zoom in/out buttons to the top right of the map.

### Default state
![image](https://user-images.githubusercontent.com/1809908/53911964-dc917a80-4025-11e9-8f45-a81e89abb2ed.png)

### Crop layer open
![image](https://user-images.githubusercontent.com/1809908/53911989-e915d300-4025-11e9-828f-bc262a25cbb6.png)

Note, when the crop layer is open, there needs to be an "X" close button to go back to the default state. Let's connect the header, legend, and opacity slider into one component.

**Comment by jfrankl** [comment]
Here's an image that can be used:

![cdl](https://user-images.githubusercontent.com/1809908/53912498-1020d480-4027-11e9-8cb5-912509a6a3df.png)
