### ISSUE TITLE
Text changes based on user feedback

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#486]
- [x] On Registration survey, change "Do you buy queens, nucs, or packages..." to "Do you regularly buy queens, nucs...."

- [x] Add note on resend activation link and registration page saying "Please check your email for an account activation link. The email may go to your spam folder, depending on your email settings."

- [x] On November survey, change "How much honey did you collect on average for each colony" to "Approximately how much honey did you collect for each colony this year?"

- [x] ~Change "Pesticide quality" to "Insecticide load". This will also mean changing the Pesticide label to Insecticide~ Moved to #488 

- [x] In user registration survey, add "Warre hive" as an option under the "what kind of equipment do you use" question

- [x] In user registration survey, change the wording of the income from bees question to read "Do you receive income from any of the following? Check all that apply."

- [x] On monthly survey, change answers to "what methods of mite management did you use?" to this list: None, formic acid, oxalic acid, thymol (apilife or apivar), amitraz (apivar), apistan, checkmite,  queen manipulation, drone remove, other

- [x] On November survey, change answers to "what methods of mite management did you use?" to this list: None, formic acid, oxalic acid, thymol (apilife or apivar), amitraz (apivar), apistan, checkmite,  queen manipulation, drone remove, other

- [x] On monthly survey, add "Bear/natural disaster" as to choice for "What do you think was the most likely cause of colony loss?"

- [x] Home should link to beescape.org and Methodology should link to beescape.org/methodology

- [x] Add link to wild bee hotel survey - http://beescape.org/wild-bees/  - in the text that displays on the survey page when the user is not logged in 

- [x] On the user survey, change the "Describe their genetics" question to "What is the stock or genetic background of your queens?"

- [x] On the user survey, change the answers for "How do you decide when to manage for Varroa?" from a text field to a multiple-choice including "mite counts, mite symptoms, time of year, or other - fill in the blank"

**Comment by fungjj92** [comment]
I spun off one of the bullets as #488 because it will require a more follow through and commitment from the client.

Also, for mite management naming I am creating tooltips to capture the references to produces i.e apivar, apilife instead.

**Comment by fungjj92** [comment]
@dboyer  Please run these tooltip descriptions by the client. I did research on these chemicals and products and this is the conclusion I came to.

<img width="619" alt="screen shot 2019-03-07 at 2 16 00 pm" src="https://user-images.githubusercontent.com/10568752/53983794-090ccb80-40e6-11e9-880b-7676b2107b28.png">
<img width="586" alt="screen shot 2019-03-07 at 2 15 57 pm" src="https://user-images.githubusercontent.com/10568752/53983813-0f9b4300-40e6-11e9-9243-cb0d6898b117.png">

**Comment by fungjj92** [comment]
- [ ] Home should link to beescape.org and Methodology should link to beescape.org/methodology

**Comment by dboyer** [comment]
The client agreed that these tool tips work. The text on the second needs to change to:

The active ingredient in Apilife and Apiguard is thymol
