### ISSUE TITLE
Add two new data fields

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#487]
- [x] On November survey, add the question "Did you treat all of the colonies in the apiary?" with answers of Yes/No

- [x] On the monthly survey, add the question "If you have an automated scale associated with this colony, please enter the hive scale ID number here." and then display a text box

**Comment by rajadain** [comment]
Do they have a preference for where to show these questions in the survey? Beginning / middle / end?

**Comment by rajadain** [comment]
Also, for the first question "Did you treat all of the colonies in the apiary?", what should be the default value applied to current accounts? I don't think we can reset the staging database as Beekeepers have been testing there, so we need to initialize this new field to either `True` or `False` for the November Surveys that have already been filled out.

**Comment by dboyer** [comment]
Let's put automated scale under the number of hive bodies and supers, right before Varroa count.

All the staging data will not be ported to production, right? In that case, setting them all to "true" is fine.

**Comment by dboyer** [comment]
@rajadain See above edit about the placement of a question
