### ISSUE TITLE
Intensify masked color differential

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#49]
When an AoI is drawn over a satellite basemap, the masking is a bit too subtle:

![screen shot 2016-11-16 at 4 41 23 pm](https://cloud.githubusercontent.com/assets/12868342/20367004/9b405e0c-ac1b-11e6-8e65-14ea420a90ce.png)

**Comment by rajadain** [comment]
MMW has a white border around the AoI in such cases. Should we have a yellow border? Or just make the dark area darker?

**Comment by mmcfarland** [comment]
:+1: for white border.

**Comment by rajadain** [comment]
Current (50% dark):

![image](https://cloud.githubusercontent.com/assets/1430060/20500390/39ef1b98-b003-11e6-8aca-7f383d69249d.png)

62.5% dark:

![image](https://cloud.githubusercontent.com/assets/1430060/20500439/6af57976-b003-11e6-8ed2-e70aad9724b4.png)

75% dark:

![image](https://cloud.githubusercontent.com/assets/1430060/20500415/5216aeca-b003-11e6-8673-ebc82d76465d.png)

**Comment by rajadain** [comment]
Here's what an MMW style stroke looks like:

![image](https://cloud.githubusercontent.com/assets/1430060/20500757/d5deae3c-b004-11e6-92a6-40e866cb99c5.png)

If that's too thick, I can make the border thinner to be more alike the wireframes, while still adding a more defined outline:

![image](https://cloud.githubusercontent.com/assets/1430060/20500817/07395b6c-b005-11e6-9dee-719eff620d5c.png)

/cc @jfrankl

**Comment by jfrankl** [comment]
Based on the screenshots, I have a slight preference for the thinner border. I think both look good, though. Down the road, we may want to make final adjustments once we see how it looks with other polygons drawn on the map.

**Comment by rajadain** [comment]
Sounds good. I'll go with the thinner border for now, and we can do more tweaks as things start to come together. Thanks for taking a look!
