### ISSUE TITLE
Adjust fields in exports

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#505]
Issue: "There isn't any way (that is obvious to us) to identify which apiaries belong to each user. There are id variables that connect the various surveys to the lat/long of each apiary (identified by an 'apiary_id'), but nothing that connects the apiary_id to the beekeeper."

Goal: People doing data analysis can understand which beekeeper submitted which survey.

Suggested Fix: Either add a CSV for Apiary (which will have the user ID) or add the user id field to the Survey CSV

**Comment by rajadain** [comment]
The Apiary table has the following fields:

* `created_at`: When the apiary was created
* `lat`: latitude (already present in Survey CSV)
* `lng`: longitude (already present in Survey CSV)
* `marker`: the label of the marker (A, B, C)
* `name`: the name of the apiary (currently reverse geocoded, not user editable)
* `scores`: a JSON of the scores
* `starred`: if it is starred or not
* `surveyed`: if it has been surveyed or not
* `updated_at`: when the apiary was updated
* `user`: who the user is
* `deleted_at`: when the apiary was deleted

Most of these fields pertain to the user interface, and outside of the scores JSON there is little subject-matter related information there.

Adding just a user id to the Survey CSV is simpler. If they can go without an export of the Apiary scores, we should go with that.

**Comment by rajadain** [comment]
However, if we also export the Apiary table, we'll make getting all the gathered data from the app easier, allowing them to piece it together however they wish. It would be more flexible. And not much more difficult than adding a field.

**Comment by dboyer** [comment]
Please note in timesheets as support hours.
