### ISSUE TITLE
Update VRTs on s3 with new raster data for several states

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#522]
The client will provide us new processed raster data for the states WI, MI, OH, NY, WV. We will want to upload the rasters to their respective staging and production folders in S3 and use GDAL to generate/update the VRTs to include said rasters. 

The command on GDAL is like:
`gdalbuildvrt <destination_vrt_name> <file1> <file2>`

It may be quicker/straightforward enough to copy & replace sections of the existing VRT with references to the new states.

**Comment by mmcfarland** [comment]
After updating these rasters with new existing state data, we'll have to determine what we do with saved project apiaries. As is, the stored values will be (potentially) out of sync with values determined going forward. We have two options we've used in the path:

1. Do nothing, project values remain point-in-time
2. Wipe out saved project values IF this will result in the values being recalculated the next time a user loads the saved apiaries (this is how it works in MMW & Pollination Mapper)

This can be done on a subsequent issue, but wanted to record it here for reflection when implementing this change.
