### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#524]
This production deployment will have a small, additional hoop to jump through.

We updated and added some new states' raster data in s3 #523 . Ordinarily adding states wouldn't require a redeploy, but in this case a raster filename ('pesticide' --> 'insecticide') changed that that necessitated a code change, too.

Upload the new VRTs and TIFs before the updated code is deployed. This is because there's a new migration that flushes the `scores` column of the `Apiary` table to ensure fresh, complete data is shown to users. We'll get no data for the insecticide field for a few minutes if anyone is pulling fresh data during deploy, but that is much preferred to the current scenario where stale cached data breaks the front end. 

- [x] copy all data from staging bucket `beekeepers-staging-data-us-east-1` to production bucket `beekeepers-production-data-us-east-1` in AWS s3
- [x] deploy (ensure migration 0015 applies, which should happen automatically)
- [x] remove stale pesticide VRTs and TIFs (any files with the word "pesticide" can be thrown out because they're no longer used, the rest of the files will get overwritten with the files copied over from staging)

**Comment by hectcastro** [comment]
Would it be possible to write out the commands necessary (whatever was used to make this happen in staging) to execute the items in the checklist? Hoping that'll help build confidence in the steps themselves, but also reduce the cognitive burden for the production release process.

**Comment by rajadain** [comment]
(depends on #525)

**Comment by fungjj92** [comment]
This is now unblocked, and the deploy instructions have been updated. Happy to pair/copy the s3 data to prod, explain further, etc.
