### ISSUE TITLE
Upgrade PostgreSQL in staging environment

### ISSUE THREAD

**Issue by rbreslow** [project-icp/bee-pollinator-app#528]
After https://github.com/project-icp/bee-pollinator-app/issues/527 is complete, upgrade PostgreSQL for RDS in staging to match the version selected.

**Comment by hectcastro** [comment]
- [ ] Install PostgreSQL 9.4 client libraries on the bastion

```console
$ wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
$ sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
$ sudo apt-get update
$ sudo apt-get install postgresql-client-9.4
```

- [ ] Create a `tmux` session and establish a connection to the database

```console
$ tmux new -s psql
$ psql -h database.service.icp.internal -U icp_bees -d icp_bees
```

- [ ] Ensure all of the database tables have been vacuumed

```sql
icp_bees=> set maintenance_work_mem='256 MB';
icp_bees=> VACUUM (FREEZE, ANALYZE, VERBOSE);
```

- [ ] Upgrade from PostgreSQL 9.4.20 to 9.5.19
- [ ] Before upgrading from PostgreSQL 9.5.x to 9.6.x, upgrade PostGIS

```sql
icp_bees=> ALTER EXTENSION postgis UPDATE;
icp_bees=> SELECT PostGIS_full_version();
```

- [ ] Ensure all of the database tables have been vacuumed

```sql
icp_bees=> set maintenance_work_mem='256 MB';
icp_bees=> VACUUM (FREEZE, ANALYZE, VERBOSE);
```

- [ ] Upgrade from PostgreSQL 9.5.19 to 9.6.15
- [ ] Upgrade PostGIS

```sql
icp_bees=> ALTER EXTENSION postgis UPDATE TO '2.5.2';
icp_bees=> SELECT PostGIS_full_version();
```

- [ ] Ensure all of the database tables have been vacuumed

```sql
icp_bees=> set maintenance_work_mem='1 GB';
icp_bees=> VACUUM (FREEZE, ANALYZE, VERBOSE);
```
