### ISSUE TITLE
Provision worker with model dependencies

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#53]
Provision the worker vm with ansible roles to support the model dependencies:
* GDAL
* TBD

**Comment by caseypt** [comment]
Blocked until other model dependencies are figured out.

**Comment by ajrobbins** [comment]
@mmcfarland is there an update on what the other model dependencies are?

**Comment by mmcfarland** [comment]
Yes, though this work is actually being done in tandem with https://github.com/project-icp/bee-pollinator-model/issues/3.  I think it was split into two cards for purpose of Waffle points.  I've assigned and moved it, sorry for the confusion.
