### ISSUE TITLE
Surveys exit suddenly on outside click

### ISSUE THREAD

**Issue by fungjj92** [project-icp/bee-pollinator-app#535]
### Overview

While I'm filling out the monthly survey, it often exits suddenly. The entered data is lost, which is a huge bummer and would greatly disincentivise using this app.

I have not observed this in other surveys, but that doesn't mean they don't have odd behavior too.

### What to do

One safety measure for surveys would be that clicking outside the dialog *does not* close the survey. Clicking outside the dialog is very easy to do. Too easy. There is a hook on reactjs-popup `closeOnDocumentClose` or something that we can flip.

Otherwise investigate why/how the monthly survey exits suddenly and remedy that such that only clicking a close or submit button closes the dialog. There is currently no close button. It's not sketched out in any wires but I think our classic "x" button would be a helpful change.

**Comment by rajadain** [comment]
Although Monthly surveys are no longer visible in the app, this bug is still seen in other kinds of surveys too. Need to fix it for all surveys.
