### ISSUE TITLE
Map Doesn't Update on New Search if Zoomed In All The Way

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#548]
If you are zoomed in all the way, searching for a new location does not update the map, until you zoom out one level, then it updates the map:

![2019-10-30 14 35 04](https://user-images.githubusercontent.com/1430060/67888610-d192d980-fb23-11e9-9968-85647a18ef21.gif)

**Comment by mmcfarland** [comment]
We will want to set up a `hotfix/1.4.1` branch so we can do a hotfix release. 

@rajadain or @fungjj92 can you coordinate with operations to make sure this gets scheduled.
