### ISSUE TITLE
Prevent entering a spring survey without a fall survey

### ISSUE THREAD

**Issue by dboyer** [project-icp/bee-pollinator-app#558]
Implement a check that prevents users from completing a Spring survey if no previous Fall survey exists for that apiary.

Should the user incorrectly begin a Spring survey, they will be prompted to exit the survey and add a Fall survey first.

**Comment by rajadain** [comment]
Swapped in this instead of #559

**Comment by rajadain** [comment]
This should be a front-end check only, no need to add validation in the back-end preventing addition of Spring surveys without corresponding Fall surveys.
