### ISSUE TITLE
Beescape Feedback Blackbox (1 point)

### ISSUE THREAD

**Issue by rajadain** [project-icp/bee-pollinator-app#570]
Initially :one: point.

**Comment by dboyer** [comment]
Two small spelling/capitalization changes to the April survey

- [ ] Capitalize November in the list of choices
- [ ] Spell adequate correctly

![Screen Shot 2020-02-27 at 11 42 12 AM](https://user-images.githubusercontent.com/516764/75465388-916b2880-5956-11ea-8520-df051736ba2e.png)
