### ISSUE TITLE
Production Deployment: 1.5.1 by 5/31

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#590]
We recently completed a data-only upgrade task (#586, #587) that did not require a redeployment of the application. We then got a request to relabel areas of the application that reference a now expanded data range, which will require a full application release.

Depends on:
* [x] #587 
* [x] #589 (completed by https://github.com/project-icp/bee-pollinator-app/pull/591)

Release branch created: https://github.com/project-icp/bee-pollinator-app/tree/release/1.5.1

**Release must be done by 5/31, when the contract funds expire.**

**Comment by mmcfarland** [comment]
All the required prerequisites are complete for the release.

https://github.com/project-icp/bee-pollinator-app/compare/master...release/1.5.1

**Comment by mmcfarland** [comment]
Note that the release artifacts have been build and the process has been completed through the "Release Testing" step of the [documentation](https://github.com/project-icp/bee-pollinator-app/blob/develop/deployment/RELEASES.md#release-testing)

**Comment by hectcastro** [comment]
Thanks for teeing this up for us so nicely. The changes have been promoted to production. I reproduced the testing instructions in https://github.com/project-icp/bee-pollinator-app/pull/591 and believe that things are working as expected.
