### ISSUE TITLE
Add opacity slider for overlay

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#66]
When toggled on, the crop overlay should display a opacity slider.  MMW has this via a leaflet plugin - the code for adding is probably there but dormant. We may need to change the orientation.

![screenshot from 2016-12-05 11 32 17](https://cloud.githubusercontent.com/assets/1014341/20893093/859ea640-bade-11e6-83e0-50c5c3f3cbce.png)

**Comment by arottersman** [comment]
@jfrankl Where do you want this thing?

<img width="215" alt="screen shot 2016-12-07 at 2 11 05 pm" src="https://cloud.githubusercontent.com/assets/7633670/20982581/30de2a68-bc87-11e6-9020-6ca57f7c94a2.png">

**Comment by jfrankl** [comment]
Let's combine it with the "Crop Layer" label into a single component. Something like this:

![image](https://cloud.githubusercontent.com/assets/1809908/20983197/8dc127e2-bc89-11e6-8d1e-96d188f45700.png)

I'm not sure if the OFF/eye button is necessary. I think we could leave it in for now and see how people respond during user testing.
