### ISSUE TITLE
Add legend

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#74]
Once the client has dictated the reclassification of the cropscape raster and we've integrated it in #58, add a legend. Need consultation from @jfrankl; will likely look like this example from MMW wireframes:

![screen shot 2016-12-09 at 10 28 00 am](https://cloud.githubusercontent.com/assets/12868342/21054100/3c4400ca-bdfa-11e6-919c-307d9576c98b.png)
 
(but without the layer selector)

**Comment by mmcfarland** [comment]
This should include finalizing the color choices for the legend with the reclassified data.  Though subjective, I think we should use the original "primary" crop color from the grouped result since presumably some thought was put into the original color selection.

**Comment by arottersman** [comment]
Will there be a way to know what crop types are visible in current viewport or will we be showing the legend with all 47 values?

**Comment by arottersman** [comment]
I created https://github.com/project-icp/bee-pollinator-app/issues/95 for the actual color choosing/application

**Comment by mmcfarland** [comment]
We won't be able to tell what's in the viewport, I think we should just do all 47 for the purpose of this card, but it's likely we'll do something like show the top 10 most common/important and then do a "show more" for the remainder, but we'll need to talk to @jfrankl for guidance.  This card can just be roughing it in.
