### ISSUE TITLE
Duplicate "Current Conditions" scenario when new scenarios are created

### ISSUE THREAD

**Issue by ajrobbins** [project-icp/bee-pollinator-app#75]
Users will be adding land cover modifications to the "Current Conditions" scenario to reclassify the land cover raster, which is often inaccurate at the farm/tract level. Any modifications they make should be automatically copied onto the New Scenario tab that is up by default, and any subsequent new scenarios.

**Comment by mmcfarland** [comment]
Closing this to break into more discrete tasks
