### ISSUE TITLE
Ingest TMS style web mercator tiles

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#82]
Ingest the raster produced from #81 and store as `z/x/y` tiles in the datahub.  Importantly, use the color scheme generated in #95

**Comment by arottersman** [comment]
The progress so far...

- Downloaded a fresh`cdl_reclass_5070.tif`from s3 today
- Followed first steps of https://github.com/azavea/azavea-data-hub/tree/master/etl to chunk it...ran
`python ../gdal/gdal/swig/python/scripts/gdal_retile.py cdl_reclass_lzw_5070.tif -of GTiff -co compress=deflate -ps 3096 3096 -targetDir .` where `./gdal/` is Rick Mohr's gdal branch that patches gdal_retile to maintain null values 

- Uploaded chunks to `s3://icp-cdl-data/cdl_reclass_chunks/`
