### ISSUE TITLE
Prevent new scenario tabs from executing bare model

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#84]
The workflow for this app is:

1. Open current conditions first
2. Add land cover corrections to augment the base raster data layer
3. Go to new scenario to start adding enhancement or changes
  * Changes from 2) will be applied to 3) and subsequent scenarios
4. Add more scenario, repeat

The scenario tab should wait to execute until the tab is switched to.  If it is switched to and it has:
* no results yet (means hasn't executed yet) _and_ current conditions does have a result: don't execute the model, just get the results from current conditions, they will be the same
* no results yet and no results in CC, then we should execute as normal.

Let's chat about implementation details.

**Comment by arottersman** [comment]
If landcover is added in a scenario should it be carried over to all subsequent scenarios?

**Comment by mmcfarland** [comment]
No, unless that scenario is the current conditions.  I was assuming that would be a separate card because it involves re-executing all the scenarios as well as managing adding and removing those modifications.  I was picturing this card being a first step toward that ultimate goal.
