### ISSUE TITLE
Chart crop yield output

### ISSUE THREAD

**Issue by mmcfarland** [project-icp/bee-pollinator-app#89]
Yield model results returns output as JSON in the format of 
```json
{
    "12": 0,
    "16": 0,
    "17": 0,
    "18": 0,
    "20": 0,
    "27": 0.8431655764579773,
    "33": 0.3809242248535156,
    "46": 0,
    "47": 0
}
```
Where the key is a CDL crop group id and the value is a measure of "yield per acre" for that crop type.  We want to display this output in a chart with the following properties:
* Vertica(?)l bar chart, one bar per crop from this scenario
* Replace crop id with crop group label (this may be done within the model, or on the client, not sure what's most beneficial)
* For crops with 0 values, don't display them
* Zip each crop for each scenario with the corresponding crop value from Current Conditions as a grouped bar.  If in that pair, one is zero and the other is non-zero, do include the crop in the chart.
* Add a class for crop id to each bar of a crop id, so we can style the bars in conjunction with the legend colors

A rough visual guide would be output like this:
![screenshot 2016-12-27 at 12 46 10 pm](https://cloud.githubusercontent.com/assets/1014341/21505177/e6681c94-cc32-11e6-92af-e1e45a5d73cb.png)

Depending on the number of classes we're reporting on, it may have to be flipped on its axis to allow longer lists of crop types.

**Comment by arottersman** [comment]
Should the work on this card carry over to the compare view charts?

**Comment by mmcfarland** [comment]
Good question, I don't think so.  It'll be a very similar chart, but I think we'll want to allow a crop dropdown to do one selected crop at a time (and without the CC next to the bar), similar to our compare output for mapshed.  Seems like enough to work to be its own card.
